# Generated by Django 4.0.4 on 2022-04-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
