# Generated by Django 4.0.4 on 2022-04-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_fileuploadv2_alter_fileupload_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
