# Generated by Django 4.0.4 on 2022-04-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_fileuploadv1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
