# Generated by Django 4.0.4 on 2022-04-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploadv1',
        ),
    ]
